# contains user-specific enviroment variables

export AUSPEX_DB_IP=""
export MSG_CONTEXT=AUSPEX
export DISCOVERY_SERVER=AUSPEX

if [ "$DISCOVERY_SERVER" == "MENTHON" ]; then
    export ROS_DISCOVERY_SERVER="192.168.51.118:11811"
elif [ "$DISCOVERY_SERVER" == "AUSPEX" ]; then
    export ROS_DISCOVERY_SERVER="192.168.50.179:11811"
else
    unset ROS_DISCOVERY_SERVER
fi

export AUSPEX_PLATFORM=TERRA
export FC_TYPE=NONE
export OBC_TYPE=NONE
export CAM_TYPE=[NONE]

export OPENAI_API_KEY="PLEASE FILL IN"
export COPERNICUS_CLIENT_ID="PLEASE FILL IN"
export COPERNICUS_CLIENT_SK="PLEASE FILL IN"
